/* Generated by Yosys 0.18+29 (git sha1 b2408df31, gcc 10.3.0-1ubuntu1~20.04 -fPIC -Os) */

module abs_diff(\in_0[0] , \in_0[1] , \in_0[2] , \in_0[3] , \in_0[4] , \in_0[5] , \in_0[6] , \in_0[7] , \in_1[0] , \in_1[1] , \in_1[2] , \in_1[3] , \in_1[4] , \in_1[5] , \in_1[6] , \in_1[7] , \res[0] , \res[1] , \res[2] , \res[3] , \res[4] 
, \res[5] , \res[6] , \res[7] , \res[8] );
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  input \in_0[0] ;
  wire \in_0[0] ;
  input \in_0[1] ;
  wire \in_0[1] ;
  input \in_0[2] ;
  wire \in_0[2] ;
  input \in_0[3] ;
  wire \in_0[3] ;
  input \in_0[4] ;
  wire \in_0[4] ;
  input \in_0[5] ;
  wire \in_0[5] ;
  input \in_0[6] ;
  wire \in_0[6] ;
  input \in_0[7] ;
  wire \in_0[7] ;
  input \in_1[0] ;
  wire \in_1[0] ;
  input \in_1[1] ;
  wire \in_1[1] ;
  input \in_1[2] ;
  wire \in_1[2] ;
  input \in_1[3] ;
  wire \in_1[3] ;
  input \in_1[4] ;
  wire \in_1[4] ;
  input \in_1[5] ;
  wire \in_1[5] ;
  input \in_1[6] ;
  wire \in_1[6] ;
  input \in_1[7] ;
  wire \in_1[7] ;
  output \res[0] ;
  wire \res[0] ;
  output \res[1] ;
  wire \res[1] ;
  output \res[2] ;
  wire \res[2] ;
  output \res[3] ;
  wire \res[3] ;
  output \res[4] ;
  wire \res[4] ;
  output \res[5] ;
  wire \res[5] ;
  output \res[6] ;
  wire \res[6] ;
  output \res[7] ;
  wire \res[7] ;
  output \res[8] ;
  wire \res[8] ;
  INV_X1 _148_ (
    .A(_082_),
    .ZN(_090_)
  );
  AND2_X1 _149_ (
    .A1(_090_),
    .A2(_074_),
    .ZN(_091_)
  );
  NOR2_X1 _150_ (
    .A1(_090_),
    .A2(_074_),
    .ZN(_092_)
  );
  NOR2_X1 _151_ (
    .A1(_091_),
    .A2(_092_),
    .ZN(_093_)
  );
  INV_X1 _152_ (
    .A(_093_),
    .ZN(_141_)
  );
  INV_X1 _153_ (
    .A(_084_),
    .ZN(_094_)
  );
  NOR2_X1 _154_ (
    .A1(_094_),
    .A2(_076_),
    .ZN(_095_)
  );
  INV_X1 _155_ (
    .A(_095_),
    .ZN(_096_)
  );
  INV_X1 _156_ (
    .A(_092_),
    .ZN(_097_)
  );
  INV_X1 _157_ (
    .A(_075_),
    .ZN(_098_)
  );
  NOR2_X1 _158_ (
    .A1(_098_),
    .A2(_083_),
    .ZN(_099_)
  );
  INV_X1 _159_ (
    .A(_099_),
    .ZN(_100_)
  );
  NAND2_X1 _160_ (
    .A1(_098_),
    .A2(_083_),
    .ZN(_101_)
  );
  INV_X1 _161_ (
    .A(_101_),
    .ZN(_102_)
  );
  OAI21_X1 _162_ (
    .A(_090_),
    .B1(_074_),
    .B2(_083_),
    .ZN(_103_)
  );
  OAI22_X1 _163_ (
    .A1(_097_),
    .A2(_100_),
    .B1(_102_),
    .B2(_103_),
    .ZN(_104_)
  );
  NAND3_X1 _164_ (
    .A1(_093_),
    .A2(_100_),
    .A3(_101_),
    .ZN(_105_)
  );
  NAND2_X1 _165_ (
    .A1(_094_),
    .A2(_076_),
    .ZN(_106_)
  );
  OAI21_X1 _166_ (
    .A(_105_),
    .B1(_093_),
    .B2(_106_),
    .ZN(_107_)
  );
  AOI21_X1 _167_ (
    .A(_107_),
    .B1(_096_),
    .B2(_104_),
    .ZN(_142_)
  );
  INV_X1 _168_ (
    .A(_079_),
    .ZN(_108_)
  );
  INV_X1 _169_ (
    .A(_077_),
    .ZN(_109_)
  );
  OAI21_X1 _170_ (
    .A(_142_),
    .B1(_085_),
    .B2(_109_),
    .ZN(_110_)
  );
  INV_X1 _171_ (
    .A(_078_),
    .ZN(_111_)
  );
  AOI22_X1 _172_ (
    .A1(_085_),
    .A2(_109_),
    .B1(_111_),
    .B2(_086_),
    .ZN(_112_)
  );
  OAI22_X1 _173_ (
    .A1(_087_),
    .A2(_108_),
    .B1(_111_),
    .B2(_086_),
    .ZN(_113_)
  );
  AOI21_X1 _174_ (
    .A(_113_),
    .B1(_110_),
    .B2(_112_),
    .ZN(_114_)
  );
  AOI21_X1 _175_ (
    .A(_114_),
    .B1(_087_),
    .B2(_108_),
    .ZN(_145_)
  );
  INV_X1 _176_ (
    .A(_145_),
    .ZN(_144_)
  );
  INV_X1 _177_ (
    .A(_080_),
    .ZN(_115_)
  );
  XNOR2_X1 _178_ (
    .A(_080_),
    .B(_088_),
    .ZN(_116_)
  );
  INV_X1 _179_ (
    .A(_116_),
    .ZN(_117_)
  );
  NOR2_X1 _180_ (
    .A1(_145_),
    .A2(_117_),
    .ZN(_118_)
  );
  AOI21_X1 _181_ (
    .A(_118_),
    .B1(_115_),
    .B2(_088_),
    .ZN(_119_)
  );
  INV_X1 _182_ (
    .A(_089_),
    .ZN(_120_)
  );
  NAND2_X1 _183_ (
    .A1(_120_),
    .A2(_081_),
    .ZN(_121_)
  );
  NOR2_X1 _184_ (
    .A1(_120_),
    .A2(_081_),
    .ZN(_122_)
  );
  NAND2_X1 _185_ (
    .A1(_119_),
    .A2(_122_),
    .ZN(_123_)
  );
  OAI21_X1 _186_ (
    .A(_123_),
    .B1(_119_),
    .B2(_121_),
    .ZN(_147_)
  );
  XNOR2_X1 _187_ (
    .A(_145_),
    .B(_117_),
    .ZN(_124_)
  );
  INV_X1 _188_ (
    .A(_122_),
    .ZN(_125_)
  );
  NAND2_X1 _189_ (
    .A1(_119_),
    .A2(_121_),
    .ZN(_126_)
  );
  NAND2_X1 _190_ (
    .A1(_126_),
    .A2(_125_),
    .ZN(_127_)
  );
  XNOR2_X1 _191_ (
    .A(_127_),
    .B(_124_),
    .ZN(_146_)
  );
  INV_X1 _192_ (
    .A(_106_),
    .ZN(_128_)
  );
  AOI21_X1 _193_ (
    .A(_095_),
    .B1(_097_),
    .B2(_128_),
    .ZN(_129_)
  );
  NAND3_X1 _194_ (
    .A1(_096_),
    .A2(_102_),
    .A3(_106_),
    .ZN(_130_)
  );
  OAI221_X1 _195_ (
    .A(_130_),
    .B1(_100_),
    .B2(_106_),
    .C1(_129_),
    .C2(_102_),
    .ZN(_131_)
  );
  NAND2_X1 _196_ (
    .A1(_127_),
    .A2(_131_),
    .ZN(_132_)
  );
  AOI21_X1 _197_ (
    .A(_099_),
    .B1(_091_),
    .B2(_094_),
    .ZN(_133_)
  );
  OAI21_X1 _198_ (
    .A(_133_),
    .B1(_095_),
    .B2(_128_),
    .ZN(_134_)
  );
  AOI21_X1 _199_ (
    .A(_091_),
    .B1(_096_),
    .B2(_099_),
    .ZN(_135_)
  );
  AOI22_X1 _200_ (
    .A1(_102_),
    .A2(_128_),
    .B1(_092_),
    .B2(_084_),
    .ZN(_136_)
  );
  OAI211_X1 _201_ (
    .A(_134_),
    .B(_136_),
    .C1(_128_),
    .C2(_135_),
    .ZN(_137_)
  );
  NAND3_X1 _202_ (
    .A1(_126_),
    .A2(_125_),
    .A3(_137_),
    .ZN(_138_)
  );
  NAND2_X1 _203_ (
    .A1(_091_),
    .A2(_095_),
    .ZN(_139_)
  );
  NAND3_X1 _204_ (
    .A1(_100_),
    .A2(_092_),
    .A3(_106_),
    .ZN(_140_)
  );
  NAND4_X1 _205_ (
    .A1(_132_),
    .A2(_138_),
    .A3(_139_),
    .A4(_140_),
    .ZN(_143_)
  );
  assign \res[5]  = 1'h0;
  assign \res[8]  = 1'h0;
  assign _081_ = \in_0[7] ;
  assign _089_ = \in_1[7] ;
  assign _080_ = \in_0[6] ;
  assign _088_ = \in_1[6] ;
  assign _085_ = \in_1[3] ;
  assign _074_ = \in_0[0] ;
  assign _082_ = \in_1[0] ;
  assign \res[0]  = _141_;
  assign _083_ = \in_1[1] ;
  assign _075_ = \in_0[1] ;
  assign _076_ = \in_0[2] ;
  assign _084_ = \in_1[2] ;
  assign \res[1]  = _142_;
  assign _077_ = \in_0[3] ;
  assign _087_ = \in_1[5] ;
  assign _079_ = \in_0[5] ;
  assign _086_ = \in_1[4] ;
  assign _078_ = \in_0[4] ;
  assign \res[3]  = _144_;
  assign \res[7]  = _147_;
  assign \res[6]  = _146_;
  assign \res[4]  = _145_;
  assign \res[2]  = _143_;
endmodule
