/* Generated by Yosys 0.18+29 (git sha1 b2408df31, gcc 10.3.0-1ubuntu1~20.04 -fPIC -Os) */

module buttfly(\in_0[0] , \in_0[1] , \in_0[2] , \in_0[3] , \in_0[4] , \in_0[5] , \in_0[6] , \in_0[7] , \in_0[8] , \in_0[9] , \in_0[10] , \in_0[11] , \in_0[12] , \in_0[13] , \in_0[14] , \in_0[15] , \in_1[0] , \in_1[1] , \in_1[2] , \in_1[3] , \in_1[4] 
, \in_1[5] , \in_1[6] , \in_1[7] , \in_1[8] , \in_1[9] , \in_1[10] , \in_1[11] , \in_1[12] , \in_1[13] , \in_1[14] , \in_1[15] , \res_0[0] , \res_0[1] , \res_0[2] , \res_0[3] , \res_0[4] , \res_0[5] , \res_0[6] , \res_0[7] , \res_0[8] , \res_0[9] 
, \res_0[10] , \res_0[11] , \res_0[12] , \res_0[13] , \res_0[14] , \res_0[15] , \res_0[16] , \res_1[0] , \res_1[1] , \res_1[2] , \res_1[3] , \res_1[4] , \res_1[5] , \res_1[6] , \res_1[7] , \res_1[8] , \res_1[9] , \res_1[10] , \res_1[11] , \res_1[12] , \res_1[13] 
, \res_1[14] , \res_1[15] , \res_1[16] );
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _400_;
  wire _401_;
  wire _402_;
  wire _403_;
  wire _404_;
  wire _405_;
  wire _406_;
  wire _407_;
  wire _408_;
  wire _409_;
  input \in_0[0] ;
  wire \in_0[0] ;
  input \in_0[10] ;
  wire \in_0[10] ;
  input \in_0[11] ;
  wire \in_0[11] ;
  input \in_0[12] ;
  wire \in_0[12] ;
  input \in_0[13] ;
  wire \in_0[13] ;
  input \in_0[14] ;
  wire \in_0[14] ;
  input \in_0[15] ;
  wire \in_0[15] ;
  input \in_0[1] ;
  wire \in_0[1] ;
  input \in_0[2] ;
  wire \in_0[2] ;
  input \in_0[3] ;
  wire \in_0[3] ;
  input \in_0[4] ;
  wire \in_0[4] ;
  input \in_0[5] ;
  wire \in_0[5] ;
  input \in_0[6] ;
  wire \in_0[6] ;
  input \in_0[7] ;
  wire \in_0[7] ;
  input \in_0[8] ;
  wire \in_0[8] ;
  input \in_0[9] ;
  wire \in_0[9] ;
  input \in_1[0] ;
  wire \in_1[0] ;
  input \in_1[10] ;
  wire \in_1[10] ;
  input \in_1[11] ;
  wire \in_1[11] ;
  input \in_1[12] ;
  wire \in_1[12] ;
  input \in_1[13] ;
  wire \in_1[13] ;
  input \in_1[14] ;
  wire \in_1[14] ;
  input \in_1[15] ;
  wire \in_1[15] ;
  input \in_1[1] ;
  wire \in_1[1] ;
  input \in_1[2] ;
  wire \in_1[2] ;
  input \in_1[3] ;
  wire \in_1[3] ;
  input \in_1[4] ;
  wire \in_1[4] ;
  input \in_1[5] ;
  wire \in_1[5] ;
  input \in_1[6] ;
  wire \in_1[6] ;
  input \in_1[7] ;
  wire \in_1[7] ;
  input \in_1[8] ;
  wire \in_1[8] ;
  input \in_1[9] ;
  wire \in_1[9] ;
  output \res_0[0] ;
  wire \res_0[0] ;
  output \res_0[10] ;
  wire \res_0[10] ;
  output \res_0[11] ;
  wire \res_0[11] ;
  output \res_0[12] ;
  wire \res_0[12] ;
  output \res_0[13] ;
  wire \res_0[13] ;
  output \res_0[14] ;
  wire \res_0[14] ;
  output \res_0[15] ;
  wire \res_0[15] ;
  output \res_0[16] ;
  wire \res_0[16] ;
  output \res_0[1] ;
  wire \res_0[1] ;
  output \res_0[2] ;
  wire \res_0[2] ;
  output \res_0[3] ;
  wire \res_0[3] ;
  output \res_0[4] ;
  wire \res_0[4] ;
  output \res_0[5] ;
  wire \res_0[5] ;
  output \res_0[6] ;
  wire \res_0[6] ;
  output \res_0[7] ;
  wire \res_0[7] ;
  output \res_0[8] ;
  wire \res_0[8] ;
  output \res_0[9] ;
  wire \res_0[9] ;
  output \res_1[0] ;
  wire \res_1[0] ;
  output \res_1[10] ;
  wire \res_1[10] ;
  output \res_1[11] ;
  wire \res_1[11] ;
  output \res_1[12] ;
  wire \res_1[12] ;
  output \res_1[13] ;
  wire \res_1[13] ;
  output \res_1[14] ;
  wire \res_1[14] ;
  output \res_1[15] ;
  wire \res_1[15] ;
  output \res_1[16] ;
  wire \res_1[16] ;
  output \res_1[1] ;
  wire \res_1[1] ;
  output \res_1[2] ;
  wire \res_1[2] ;
  output \res_1[3] ;
  wire \res_1[3] ;
  output \res_1[4] ;
  wire \res_1[4] ;
  output \res_1[5] ;
  wire \res_1[5] ;
  output \res_1[6] ;
  wire \res_1[6] ;
  output \res_1[7] ;
  wire \res_1[7] ;
  output \res_1[8] ;
  wire \res_1[8] ;
  output \res_1[9] ;
  wire \res_1[9] ;
  XOR2_X1 _410_ (
    .A(_276_),
    .B(_260_),
    .Z(_346_)
  );
  INV_X1 _411_ (
    .A(_268_),
    .ZN(_347_)
  );
  NOR2_X1 _412_ (
    .A1(_347_),
    .A2(_252_),
    .ZN(_348_)
  );
  NOR2_X1 _413_ (
    .A1(_275_),
    .A2(_259_),
    .ZN(_349_)
  );
  INV_X1 _414_ (
    .A(_349_),
    .ZN(_350_)
  );
  NAND2_X1 _415_ (
    .A1(_275_),
    .A2(_259_),
    .ZN(_351_)
  );
  NAND2_X1 _416_ (
    .A1(_350_),
    .A2(_351_),
    .ZN(_352_)
  );
  INV_X1 _417_ (
    .A(_275_),
    .ZN(_353_)
  );
  NOR2_X1 _418_ (
    .A1(_353_),
    .A2(_259_),
    .ZN(_354_)
  );
  AOI21_X1 _419_ (
    .A(_354_),
    .B1(_352_),
    .B2(_348_),
    .ZN(_355_)
  );
  XNOR2_X1 _420_ (
    .A(_355_),
    .B(_346_),
    .ZN(_404_)
  );
  XOR2_X1 _421_ (
    .A(_262_),
    .B(_278_),
    .Z(_356_)
  );
  INV_X1 _422_ (
    .A(_277_),
    .ZN(_357_)
  );
  NOR2_X1 _423_ (
    .A1(_357_),
    .A2(_261_),
    .ZN(_358_)
  );
  XOR2_X1 _424_ (
    .A(_277_),
    .B(_261_),
    .Z(_359_)
  );
  INV_X1 _425_ (
    .A(_359_),
    .ZN(_360_)
  );
  AOI21_X1 _426_ (
    .A(_358_),
    .B1(_404_),
    .B2(_360_),
    .ZN(_361_)
  );
  XNOR2_X1 _427_ (
    .A(_361_),
    .B(_356_),
    .ZN(_406_)
  );
  XOR2_X1 _428_ (
    .A(_267_),
    .B(_283_),
    .Z(_362_)
  );
  INV_X1 _429_ (
    .A(_266_),
    .ZN(_363_)
  );
  INV_X1 _430_ (
    .A(_282_),
    .ZN(_364_)
  );
  INV_X1 _431_ (
    .A(_265_),
    .ZN(_365_)
  );
  NAND2_X1 _432_ (
    .A1(_365_),
    .A2(_281_),
    .ZN(_366_)
  );
  INV_X1 _433_ (
    .A(_280_),
    .ZN(_367_)
  );
  XNOR2_X1 _434_ (
    .A(_280_),
    .B(_264_),
    .ZN(_368_)
  );
  INV_X1 _435_ (
    .A(_368_),
    .ZN(_369_)
  );
  NOR2_X1 _436_ (
    .A1(_406_),
    .A2(_369_),
    .ZN(_370_)
  );
  AOI21_X1 _437_ (
    .A(_370_),
    .B1(_367_),
    .B2(_264_),
    .ZN(_371_)
  );
  OAI21_X1 _438_ (
    .A(_371_),
    .B1(_365_),
    .B2(_281_),
    .ZN(_372_)
  );
  AOI22_X1 _439_ (
    .A1(_372_),
    .A2(_366_),
    .B1(_364_),
    .B2(_266_),
    .ZN(_373_)
  );
  AOI21_X1 _440_ (
    .A(_373_),
    .B1(_282_),
    .B2(_363_),
    .ZN(_374_)
  );
  XNOR2_X1 _441_ (
    .A(_374_),
    .B(_362_),
    .ZN(_397_)
  );
  XNOR2_X1 _442_ (
    .A(_258_),
    .B(_274_),
    .ZN(_375_)
  );
  INV_X1 _443_ (
    .A(_273_),
    .ZN(_376_)
  );
  NAND2_X1 _444_ (
    .A1(_376_),
    .A2(_257_),
    .ZN(_377_)
  );
  XNOR2_X1 _445_ (
    .A(_257_),
    .B(_273_),
    .ZN(_378_)
  );
  INV_X1 _446_ (
    .A(_378_),
    .ZN(_379_)
  );
  INV_X1 _447_ (
    .A(_256_),
    .ZN(_284_)
  );
  NOR2_X1 _448_ (
    .A1(_284_),
    .A2(_272_),
    .ZN(_285_)
  );
  NAND2_X1 _449_ (
    .A1(_284_),
    .A2(_272_),
    .ZN(_286_)
  );
  INV_X1 _450_ (
    .A(_255_),
    .ZN(_287_)
  );
  INV_X1 _451_ (
    .A(_270_),
    .ZN(_288_)
  );
  NAND2_X1 _452_ (
    .A1(_288_),
    .A2(_254_),
    .ZN(_289_)
  );
  XNOR2_X1 _453_ (
    .A(_270_),
    .B(_254_),
    .ZN(_290_)
  );
  INV_X1 _454_ (
    .A(_290_),
    .ZN(_291_)
  );
  OAI21_X1 _455_ (
    .A(_289_),
    .B1(_397_),
    .B2(_291_),
    .ZN(_292_)
  );
  XNOR2_X1 _456_ (
    .A(_271_),
    .B(_255_),
    .ZN(_293_)
  );
  NAND2_X1 _457_ (
    .A1(_292_),
    .A2(_293_),
    .ZN(_294_)
  );
  OAI21_X1 _458_ (
    .A(_294_),
    .B1(_271_),
    .B2(_287_),
    .ZN(_295_)
  );
  AOI21_X1 _459_ (
    .A(_285_),
    .B1(_295_),
    .B2(_286_),
    .ZN(_296_)
  );
  OAI21_X1 _460_ (
    .A(_377_),
    .B1(_296_),
    .B2(_379_),
    .ZN(_297_)
  );
  XOR2_X1 _461_ (
    .A(_297_),
    .B(_375_),
    .Z(_402_)
  );
  INV_X1 _462_ (
    .A(_285_),
    .ZN(_298_)
  );
  AND2_X1 _463_ (
    .A1(_298_),
    .A2(_286_),
    .ZN(_299_)
  );
  XOR2_X1 _464_ (
    .A(_295_),
    .B(_299_),
    .Z(_400_)
  );
  XOR2_X1 _465_ (
    .A(_292_),
    .B(_293_),
    .Z(_399_)
  );
  XNOR2_X1 _466_ (
    .A(_397_),
    .B(_290_),
    .ZN(_398_)
  );
  NAND2_X1 _467_ (
    .A1(_372_),
    .A2(_366_),
    .ZN(_300_)
  );
  NOR2_X1 _468_ (
    .A1(_364_),
    .A2(_363_),
    .ZN(_301_)
  );
  NOR2_X1 _469_ (
    .A1(_282_),
    .A2(_266_),
    .ZN(_302_)
  );
  NOR2_X1 _470_ (
    .A1(_301_),
    .A2(_302_),
    .ZN(_303_)
  );
  XOR2_X1 _471_ (
    .A(_300_),
    .B(_303_),
    .Z(_409_)
  );
  NAND2_X1 _472_ (
    .A1(_265_),
    .A2(_281_),
    .ZN(_304_)
  );
  NOR2_X1 _473_ (
    .A1(_265_),
    .A2(_281_),
    .ZN(_305_)
  );
  INV_X1 _474_ (
    .A(_305_),
    .ZN(_306_)
  );
  NAND2_X1 _475_ (
    .A1(_306_),
    .A2(_304_),
    .ZN(_307_)
  );
  XNOR2_X1 _476_ (
    .A(_371_),
    .B(_307_),
    .ZN(_408_)
  );
  XNOR2_X1 _477_ (
    .A(_406_),
    .B(_368_),
    .ZN(_407_)
  );
  XNOR2_X1 _478_ (
    .A(_404_),
    .B(_360_),
    .ZN(_405_)
  );
  XNOR2_X1 _479_ (
    .A(_352_),
    .B(_348_),
    .ZN(_403_)
  );
  NOR2_X1 _480_ (
    .A1(_258_),
    .A2(_274_),
    .ZN(_308_)
  );
  NAND2_X1 _481_ (
    .A1(_258_),
    .A2(_274_),
    .ZN(_309_)
  );
  NOR2_X1 _482_ (
    .A1(_257_),
    .A2(_273_),
    .ZN(_310_)
  );
  INV_X1 _483_ (
    .A(_272_),
    .ZN(_311_)
  );
  INV_X1 _484_ (
    .A(_271_),
    .ZN(_312_)
  );
  INV_X1 _485_ (
    .A(_254_),
    .ZN(_313_)
  );
  NOR2_X1 _486_ (
    .A1(_253_),
    .A2(_269_),
    .ZN(_314_)
  );
  NAND2_X1 _487_ (
    .A1(_253_),
    .A2(_269_),
    .ZN(_315_)
  );
  INV_X1 _488_ (
    .A(_302_),
    .ZN(_316_)
  );
  AND2_X1 _489_ (
    .A1(_280_),
    .A2(_264_),
    .ZN(_317_)
  );
  NOR2_X1 _490_ (
    .A1(_263_),
    .A2(_279_),
    .ZN(_318_)
  );
  AND2_X1 _491_ (
    .A1(_277_),
    .A2(_261_),
    .ZN(_319_)
  );
  NAND2_X1 _492_ (
    .A1(_276_),
    .A2(_260_),
    .ZN(_320_)
  );
  NAND2_X1 _493_ (
    .A1(_252_),
    .A2(_268_),
    .ZN(_321_)
  );
  OAI21_X1 _494_ (
    .A(_351_),
    .B1(_349_),
    .B2(_321_),
    .ZN(_322_)
  );
  NAND2_X1 _495_ (
    .A1(_346_),
    .A2(_322_),
    .ZN(_323_)
  );
  NAND2_X1 _496_ (
    .A1(_323_),
    .A2(_320_),
    .ZN(_324_)
  );
  AOI21_X1 _497_ (
    .A(_319_),
    .B1(_324_),
    .B2(_359_),
    .ZN(_325_)
  );
  NAND2_X1 _498_ (
    .A1(_325_),
    .A2(_356_),
    .ZN(_326_)
  );
  OAI21_X1 _499_ (
    .A(_326_),
    .B1(_262_),
    .B2(_278_),
    .ZN(_327_)
  );
  XOR2_X1 _500_ (
    .A(_263_),
    .B(_279_),
    .Z(_328_)
  );
  AOI21_X1 _501_ (
    .A(_318_),
    .B1(_327_),
    .B2(_328_),
    .ZN(_329_)
  );
  AOI21_X1 _502_ (
    .A(_317_),
    .B1(_329_),
    .B2(_369_),
    .ZN(_330_)
  );
  AOI21_X1 _503_ (
    .A(_305_),
    .B1(_330_),
    .B2(_304_),
    .ZN(_331_)
  );
  OAI21_X1 _504_ (
    .A(_316_),
    .B1(_331_),
    .B2(_301_),
    .ZN(_332_)
  );
  NAND2_X1 _505_ (
    .A1(_332_),
    .A2(_362_),
    .ZN(_333_)
  );
  OAI21_X1 _506_ (
    .A(_333_),
    .B1(_267_),
    .B2(_283_),
    .ZN(_334_)
  );
  AOI21_X1 _507_ (
    .A(_314_),
    .B1(_334_),
    .B2(_315_),
    .ZN(_335_)
  );
  NOR2_X1 _508_ (
    .A1(_335_),
    .A2(_290_),
    .ZN(_336_)
  );
  AOI21_X1 _509_ (
    .A(_336_),
    .B1(_288_),
    .B2(_313_),
    .ZN(_337_)
  );
  NOR2_X1 _510_ (
    .A1(_337_),
    .A2(_293_),
    .ZN(_338_)
  );
  AOI21_X1 _511_ (
    .A(_338_),
    .B1(_312_),
    .B2(_287_),
    .ZN(_339_)
  );
  NOR2_X1 _512_ (
    .A1(_339_),
    .A2(_299_),
    .ZN(_340_)
  );
  AOI21_X1 _513_ (
    .A(_340_),
    .B1(_284_),
    .B2(_311_),
    .ZN(_341_)
  );
  INV_X1 _514_ (
    .A(_341_),
    .ZN(_342_)
  );
  AOI21_X1 _515_ (
    .A(_310_),
    .B1(_342_),
    .B2(_379_),
    .ZN(_343_)
  );
  AOI21_X1 _516_ (
    .A(_308_),
    .B1(_343_),
    .B2(_309_),
    .ZN(_387_)
  );
  XNOR2_X1 _517_ (
    .A(_343_),
    .B(_375_),
    .ZN(_386_)
  );
  XNOR2_X1 _518_ (
    .A(_341_),
    .B(_378_),
    .ZN(_385_)
  );
  XNOR2_X1 _519_ (
    .A(_339_),
    .B(_299_),
    .ZN(_384_)
  );
  XNOR2_X1 _520_ (
    .A(_337_),
    .B(_293_),
    .ZN(_383_)
  );
  XNOR2_X1 _521_ (
    .A(_335_),
    .B(_290_),
    .ZN(_382_)
  );
  INV_X1 _522_ (
    .A(_315_),
    .ZN(_344_)
  );
  NOR2_X1 _523_ (
    .A1(_344_),
    .A2(_314_),
    .ZN(_345_)
  );
  XNOR2_X1 _524_ (
    .A(_334_),
    .B(_345_),
    .ZN(_381_)
  );
  XNOR2_X1 _525_ (
    .A(_332_),
    .B(_362_),
    .ZN(_396_)
  );
  XOR2_X1 _526_ (
    .A(_331_),
    .B(_303_),
    .Z(_395_)
  );
  XOR2_X1 _527_ (
    .A(_330_),
    .B(_307_),
    .Z(_394_)
  );
  XNOR2_X1 _528_ (
    .A(_329_),
    .B(_368_),
    .ZN(_393_)
  );
  XNOR2_X1 _529_ (
    .A(_327_),
    .B(_328_),
    .ZN(_392_)
  );
  XNOR2_X1 _530_ (
    .A(_325_),
    .B(_356_),
    .ZN(_391_)
  );
  XNOR2_X1 _531_ (
    .A(_324_),
    .B(_360_),
    .ZN(_390_)
  );
  XOR2_X1 _532_ (
    .A(_346_),
    .B(_322_),
    .Z(_389_)
  );
  XOR2_X1 _533_ (
    .A(_352_),
    .B(_321_),
    .Z(_388_)
  );
  XOR2_X1 _534_ (
    .A(_252_),
    .B(_268_),
    .Z(_380_)
  );
  XNOR2_X1 _535_ (
    .A(_296_),
    .B(_378_),
    .ZN(_401_)
  );
  assign \res_1[0]  = \res_0[0] ;
  assign \res_1[16]  = \res_1[15] ;
  assign \res_1[5]  = \res_1[4] ;
  assign \res_1[9]  = \res_1[10] ;
  assign _258_ = \in_0[15] ;
  assign _274_ = \in_1[15] ;
  assign _257_ = \in_0[14] ;
  assign _273_ = \in_1[14] ;
  assign _271_ = \in_1[12] ;
  assign _255_ = \in_0[12] ;
  assign _270_ = \in_1[11] ;
  assign _254_ = \in_0[11] ;
  assign _265_ = \in_0[7] ;
  assign _281_ = \in_1[7] ;
  assign _280_ = \in_1[6] ;
  assign _264_ = \in_0[6] ;
  assign _252_ = \in_0[0] ;
  assign _268_ = \in_1[0] ;
  assign _275_ = \in_1[1] ;
  assign _259_ = \in_0[1] ;
  assign _276_ = \in_1[2] ;
  assign _260_ = \in_0[2] ;
  assign _277_ = \in_1[3] ;
  assign _261_ = \in_0[3] ;
  assign _263_ = \in_0[5] ;
  assign _279_ = \in_1[5] ;
  assign _262_ = \in_0[4] ;
  assign _278_ = \in_1[4] ;
  assign _282_ = \in_1[8] ;
  assign _266_ = \in_0[8] ;
  assign _253_ = \in_0[10] ;
  assign _269_ = \in_1[10] ;
  assign _267_ = \in_0[9] ;
  assign _283_ = \in_1[9] ;
  assign \res_1[2]  = _404_;
  assign \res_1[4]  = _406_;
  assign \res_1[10]  = _397_;
  assign _256_ = \in_0[13] ;
  assign _272_ = \in_1[13] ;
  assign \res_1[15]  = _402_;
  assign \res_1[13]  = _400_;
  assign \res_1[12]  = _399_;
  assign \res_1[11]  = _398_;
  assign \res_1[8]  = _409_;
  assign \res_1[7]  = _408_;
  assign \res_1[6]  = _407_;
  assign \res_1[3]  = _405_;
  assign \res_1[1]  = _403_;
  assign \res_0[16]  = _387_;
  assign \res_0[15]  = _386_;
  assign \res_0[14]  = _385_;
  assign \res_0[13]  = _384_;
  assign \res_0[12]  = _383_;
  assign \res_0[11]  = _382_;
  assign \res_0[10]  = _381_;
  assign \res_0[9]  = _396_;
  assign \res_0[8]  = _395_;
  assign \res_0[7]  = _394_;
  assign \res_0[6]  = _393_;
  assign \res_0[5]  = _392_;
  assign \res_0[4]  = _391_;
  assign \res_0[3]  = _390_;
  assign \res_0[2]  = _389_;
  assign \res_0[1]  = _388_;
  assign \res_0[0]  = _380_;
  assign \res_1[14]  = _401_;
endmodule
