/* Generated by Yosys 0.18+29 (git sha1 b2408df31, gcc 10.3.0-1ubuntu1~20.04 -fPIC -Os) */

module adder32(\in1[0] , \in1[1] , \in1[2] , \in1[3] , \in1[4] , \in1[5] , \in1[6] , \in1[7] , \in1[8] , \in1[9] , \in1[10] , \in1[11] , \in1[12] , \in1[13] , \in1[14] , \in1[15] , \in1[16] , \in1[17] , \in1[18] , \in1[19] , \in1[20] 
, \in1[21] , \in1[22] , \in1[23] , \in1[24] , \in1[25] , \in1[26] , \in1[27] , \in1[28] , \in1[29] , \in1[30] , \in1[31] , \in2[0] , \in2[1] , \in2[2] , \in2[3] , \in2[4] , \in2[5] , \in2[6] , \in2[7] , \in2[8] , \in2[9] 
, \in2[10] , \in2[11] , \in2[12] , \in2[13] , \in2[14] , \in2[15] , \in2[16] , \in2[17] , \in2[18] , \in2[19] , \in2[20] , \in2[21] , \in2[22] , \in2[23] , \in2[24] , \in2[25] , \in2[26] , \in2[27] , \in2[28] , \in2[29] , \in2[30] 
, \in2[31] , \res[0] , \res[1] , \res[2] , \res[3] , \res[4] , \res[5] , \res[6] , \res[7] , \res[8] , \res[9] , \res[10] , \res[11] , \res[12] , \res[13] , \res[14] , \res[15] , \res[16] , \res[17] , \res[18] , \res[19] 
, \res[20] , \res[21] , \res[22] , \res[23] , \res[24] , \res[25] , \res[26] , \res[27] , \res[28] , \res[29] , \res[30] , \res[31] , \res[32] );
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  input \in1[0] ;
  wire \in1[0] ;
  input \in1[10] ;
  wire \in1[10] ;
  input \in1[11] ;
  wire \in1[11] ;
  input \in1[12] ;
  wire \in1[12] ;
  input \in1[13] ;
  wire \in1[13] ;
  input \in1[14] ;
  wire \in1[14] ;
  input \in1[15] ;
  wire \in1[15] ;
  input \in1[16] ;
  wire \in1[16] ;
  input \in1[17] ;
  wire \in1[17] ;
  input \in1[18] ;
  wire \in1[18] ;
  input \in1[19] ;
  wire \in1[19] ;
  input \in1[1] ;
  wire \in1[1] ;
  input \in1[20] ;
  wire \in1[20] ;
  input \in1[21] ;
  wire \in1[21] ;
  input \in1[22] ;
  wire \in1[22] ;
  input \in1[23] ;
  wire \in1[23] ;
  input \in1[24] ;
  wire \in1[24] ;
  input \in1[25] ;
  wire \in1[25] ;
  input \in1[26] ;
  wire \in1[26] ;
  input \in1[27] ;
  wire \in1[27] ;
  input \in1[28] ;
  wire \in1[28] ;
  input \in1[29] ;
  wire \in1[29] ;
  input \in1[2] ;
  wire \in1[2] ;
  input \in1[30] ;
  wire \in1[30] ;
  input \in1[31] ;
  wire \in1[31] ;
  input \in1[3] ;
  wire \in1[3] ;
  input \in1[4] ;
  wire \in1[4] ;
  input \in1[5] ;
  wire \in1[5] ;
  input \in1[6] ;
  wire \in1[6] ;
  input \in1[7] ;
  wire \in1[7] ;
  input \in1[8] ;
  wire \in1[8] ;
  input \in1[9] ;
  wire \in1[9] ;
  input \in2[0] ;
  wire \in2[0] ;
  input \in2[10] ;
  wire \in2[10] ;
  input \in2[11] ;
  wire \in2[11] ;
  input \in2[12] ;
  wire \in2[12] ;
  input \in2[13] ;
  wire \in2[13] ;
  input \in2[14] ;
  wire \in2[14] ;
  input \in2[15] ;
  wire \in2[15] ;
  input \in2[16] ;
  wire \in2[16] ;
  input \in2[17] ;
  wire \in2[17] ;
  input \in2[18] ;
  wire \in2[18] ;
  input \in2[19] ;
  wire \in2[19] ;
  input \in2[1] ;
  wire \in2[1] ;
  input \in2[20] ;
  wire \in2[20] ;
  input \in2[21] ;
  wire \in2[21] ;
  input \in2[22] ;
  wire \in2[22] ;
  input \in2[23] ;
  wire \in2[23] ;
  input \in2[24] ;
  wire \in2[24] ;
  input \in2[25] ;
  wire \in2[25] ;
  input \in2[26] ;
  wire \in2[26] ;
  input \in2[27] ;
  wire \in2[27] ;
  input \in2[28] ;
  wire \in2[28] ;
  input \in2[29] ;
  wire \in2[29] ;
  input \in2[2] ;
  wire \in2[2] ;
  input \in2[30] ;
  wire \in2[30] ;
  input \in2[31] ;
  wire \in2[31] ;
  input \in2[3] ;
  wire \in2[3] ;
  input \in2[4] ;
  wire \in2[4] ;
  input \in2[5] ;
  wire \in2[5] ;
  input \in2[6] ;
  wire \in2[6] ;
  input \in2[7] ;
  wire \in2[7] ;
  input \in2[8] ;
  wire \in2[8] ;
  input \in2[9] ;
  wire \in2[9] ;
  output \res[0] ;
  wire \res[0] ;
  output \res[10] ;
  wire \res[10] ;
  output \res[11] ;
  wire \res[11] ;
  output \res[12] ;
  wire \res[12] ;
  output \res[13] ;
  wire \res[13] ;
  output \res[14] ;
  wire \res[14] ;
  output \res[15] ;
  wire \res[15] ;
  output \res[16] ;
  wire \res[16] ;
  output \res[17] ;
  wire \res[17] ;
  output \res[18] ;
  wire \res[18] ;
  output \res[19] ;
  wire \res[19] ;
  output \res[1] ;
  wire \res[1] ;
  output \res[20] ;
  wire \res[20] ;
  output \res[21] ;
  wire \res[21] ;
  output \res[22] ;
  wire \res[22] ;
  output \res[23] ;
  wire \res[23] ;
  output \res[24] ;
  wire \res[24] ;
  output \res[25] ;
  wire \res[25] ;
  output \res[26] ;
  wire \res[26] ;
  output \res[27] ;
  wire \res[27] ;
  output \res[28] ;
  wire \res[28] ;
  output \res[29] ;
  wire \res[29] ;
  output \res[2] ;
  wire \res[2] ;
  output \res[30] ;
  wire \res[30] ;
  output \res[31] ;
  wire \res[31] ;
  output \res[32] ;
  wire \res[32] ;
  output \res[3] ;
  wire \res[3] ;
  output \res[4] ;
  wire \res[4] ;
  output \res[5] ;
  wire \res[5] ;
  output \res[6] ;
  wire \res[6] ;
  output \res[7] ;
  wire \res[7] ;
  output \res[8] ;
  wire \res[8] ;
  output \res[9] ;
  wire \res[9] ;
  XNOR2_X1 _167_ (
    .A(_081_),
    .B(_098_),
    .ZN(_150_)
  );
  XOR2_X1 _168_ (
    .A(_089_),
    .B(_106_),
    .Z(_115_)
  );
  NAND2_X1 _169_ (
    .A1(_088_),
    .A2(_105_),
    .ZN(_116_)
  );
  XOR2_X1 _170_ (
    .A(_088_),
    .B(_105_),
    .Z(_117_)
  );
  OR2_X1 _171_ (
    .A1(_087_),
    .A2(_104_),
    .ZN(_118_)
  );
  XNOR2_X1 _172_ (
    .A(_103_),
    .B(_086_),
    .ZN(_119_)
  );
  NOR2_X1 _173_ (
    .A1(_085_),
    .A2(_102_),
    .ZN(_120_)
  );
  NAND2_X1 _174_ (
    .A1(_085_),
    .A2(_102_),
    .ZN(_121_)
  );
  NOR2_X1 _175_ (
    .A1(_084_),
    .A2(_101_),
    .ZN(_122_)
  );
  AOI21_X1 _176_ (
    .A(_120_),
    .B1(_121_),
    .B2(_122_),
    .ZN(_123_)
  );
  XNOR2_X1 _177_ (
    .A(_123_),
    .B(_119_),
    .ZN(_155_)
  );
  XOR2_X1 _178_ (
    .A(_087_),
    .B(_104_),
    .Z(_124_)
  );
  NAND2_X1 _179_ (
    .A1(_155_),
    .A2(_124_),
    .ZN(_125_)
  );
  NAND3_X1 _180_ (
    .A1(_125_),
    .A2(_117_),
    .A3(_118_),
    .ZN(_126_)
  );
  NAND2_X1 _181_ (
    .A1(_126_),
    .A2(_116_),
    .ZN(_127_)
  );
  XOR2_X1 _182_ (
    .A(_127_),
    .B(_115_),
    .Z(_158_)
  );
  NAND2_X1 _183_ (
    .A1(_111_),
    .A2(_094_),
    .ZN(_128_)
  );
  XOR2_X1 _184_ (
    .A(_111_),
    .B(_094_),
    .Z(_129_)
  );
  NAND2_X1 _185_ (
    .A1(_110_),
    .A2(_093_),
    .ZN(_130_)
  );
  XNOR2_X1 _186_ (
    .A(_110_),
    .B(_093_),
    .ZN(_131_)
  );
  XOR2_X1 _187_ (
    .A(_108_),
    .B(_091_),
    .Z(_132_)
  );
  INV_X1 _188_ (
    .A(_132_),
    .ZN(_133_)
  );
  NOR2_X1 _189_ (
    .A1(_158_),
    .A2(_133_),
    .ZN(_134_)
  );
  AOI21_X1 _190_ (
    .A(_134_),
    .B1(_108_),
    .B2(_091_),
    .ZN(_135_)
  );
  XNOR2_X1 _191_ (
    .A(_109_),
    .B(_092_),
    .ZN(_136_)
  );
  NOR2_X1 _192_ (
    .A1(_135_),
    .A2(_136_),
    .ZN(_137_)
  );
  AOI21_X1 _193_ (
    .A(_137_),
    .B1(_109_),
    .B2(_092_),
    .ZN(_138_)
  );
  OAI21_X1 _194_ (
    .A(_130_),
    .B1(_138_),
    .B2(_131_),
    .ZN(_139_)
  );
  NAND2_X1 _195_ (
    .A1(_139_),
    .A2(_129_),
    .ZN(_140_)
  );
  NAND2_X1 _196_ (
    .A1(_140_),
    .A2(_128_),
    .ZN(_164_)
  );
  XOR2_X1 _197_ (
    .A(_139_),
    .B(_129_),
    .Z(_163_)
  );
  XOR2_X1 _198_ (
    .A(_138_),
    .B(_131_),
    .Z(_162_)
  );
  XOR2_X1 _199_ (
    .A(_135_),
    .B(_136_),
    .Z(_161_)
  );
  NAND2_X1 _200_ (
    .A1(_089_),
    .A2(_106_),
    .ZN(_141_)
  );
  NAND2_X1 _201_ (
    .A1(_127_),
    .A2(_115_),
    .ZN(_142_)
  );
  NAND2_X1 _202_ (
    .A1(_142_),
    .A2(_141_),
    .ZN(_143_)
  );
  XNOR2_X1 _203_ (
    .A(_107_),
    .B(_090_),
    .ZN(_144_)
  );
  XNOR2_X1 _204_ (
    .A(_143_),
    .B(_144_),
    .ZN(_159_)
  );
  NAND2_X1 _205_ (
    .A1(_125_),
    .A2(_118_),
    .ZN(_145_)
  );
  XNOR2_X1 _206_ (
    .A(_145_),
    .B(_117_),
    .ZN(_157_)
  );
  INV_X1 _207_ (
    .A(_120_),
    .ZN(_146_)
  );
  NAND2_X1 _208_ (
    .A1(_146_),
    .A2(_121_),
    .ZN(_147_)
  );
  XOR2_X1 _209_ (
    .A(_147_),
    .B(_122_),
    .Z(_154_)
  );
  XOR2_X1 _210_ (
    .A(_100_),
    .B(_083_),
    .Z(_152_)
  );
  XOR2_X1 _211_ (
    .A(_082_),
    .B(_099_),
    .Z(_148_)
  );
  XNOR2_X1 _212_ (
    .A(_148_),
    .B(_150_),
    .ZN(_151_)
  );
  XNOR2_X1 _213_ (
    .A(_096_),
    .B(_113_),
    .ZN(_166_)
  );
  XOR2_X1 _214_ (
    .A(_080_),
    .B(_097_),
    .Z(_149_)
  );
  XOR2_X1 _215_ (
    .A(_095_),
    .B(_112_),
    .Z(_114_)
  );
  XNOR2_X1 _216_ (
    .A(_149_),
    .B(_114_),
    .ZN(_165_)
  );
  XNOR2_X1 _217_ (
    .A(_084_),
    .B(_101_),
    .ZN(_153_)
  );
  XNOR2_X1 _218_ (
    .A(_158_),
    .B(_132_),
    .ZN(_160_)
  );
  XNOR2_X1 _219_ (
    .A(_155_),
    .B(_124_),
    .ZN(_156_)
  );
  assign \res[10]  = 1'h0;
  assign \res[11]  = 1'h1;
  assign \res[13]  = 1'h1;
  assign \res[14]  = 1'h0;
  assign \res[16]  = 1'h0;
  assign \res[18]  = 1'h0;
  assign \res[19]  = 1'h1;
  assign \res[1]  = 1'h0;
  assign \res[23]  = 1'h1;
  assign \res[2]  = 1'h0;
  assign \res[4]  = 1'h0;
  assign \res[5]  = 1'h1;
  assign \res[6]  = 1'h0;
  assign \res[8]  = 1'h0;
  assign \res[9]  = 1'h1;
  assign _081_ = \in1[12] ;
  assign _098_ = \in2[12] ;
  assign \res[12]  = _150_;
  assign _089_ = \in1[26] ;
  assign _106_ = \in2[26] ;
  assign _087_ = \in1[24] ;
  assign _104_ = \in2[24] ;
  assign _103_ = \in2[22] ;
  assign _086_ = \in1[22] ;
  assign _085_ = \in1[21] ;
  assign _102_ = \in2[21] ;
  assign _084_ = \in1[20] ;
  assign _101_ = \in2[20] ;
  assign _088_ = \in1[25] ;
  assign _105_ = \in2[25] ;
  assign \res[26]  = _158_;
  assign \res[22]  = _155_;
  assign _111_ = \in2[31] ;
  assign _094_ = \in1[31] ;
  assign _110_ = \in2[30] ;
  assign _093_ = \in1[30] ;
  assign _109_ = \in2[29] ;
  assign _092_ = \in1[29] ;
  assign _108_ = \in2[28] ;
  assign _091_ = \in1[28] ;
  assign \res[32]  = _164_;
  assign \res[31]  = _163_;
  assign \res[30]  = _162_;
  assign \res[29]  = _161_;
  assign _107_ = \in2[27] ;
  assign _090_ = \in1[27] ;
  assign \res[27]  = _159_;
  assign \res[25]  = _157_;
  assign \res[21]  = _154_;
  assign _100_ = \in2[17] ;
  assign _083_ = \in1[17] ;
  assign \res[17]  = _152_;
  assign _082_ = \in1[15] ;
  assign _099_ = \in2[15] ;
  assign \res[15]  = _151_;
  assign _096_ = \in1[7] ;
  assign _113_ = \in2[7] ;
  assign \res[7]  = _166_;
  assign _095_ = \in1[3] ;
  assign _112_ = \in2[3] ;
  assign _080_ = \in1[0] ;
  assign _097_ = \in2[0] ;
  assign \res[3]  = _165_;
  assign \res[20]  = _153_;
  assign \res[28]  = _160_;
  assign \res[24]  = _156_;
  assign \res[0]  = _149_;
endmodule
