/* Generated by Yosys 0.18+29 (git sha1 b2408df31, gcc 10.3.0-1ubuntu1~20.04 -fPIC -Os) */

module adder16(\in1[0] , \in1[1] , \in1[2] , \in1[3] , \in1[4] , \in1[5] , \in1[6] , \in1[7] , \in1[8] , \in1[9] , \in1[10] , \in1[11] , \in1[12] , \in1[13] , \in1[14] , \in1[15] , \in2[0] , \in2[1] , \in2[2] , \in2[3] , \in2[4] 
, \in2[5] , \in2[6] , \in2[7] , \in2[8] , \in2[9] , \in2[10] , \in2[11] , \in2[12] , \in2[13] , \in2[14] , \in2[15] , \res[0] , \res[1] , \res[2] , \res[3] , \res[4] , \res[5] , \res[6] , \res[7] , \res[8] , \res[9] 
, \res[10] , \res[11] , \res[12] , \res[13] , \res[14] , \res[15] , \res[16] );
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  input \in1[0] ;
  wire \in1[0] ;
  input \in1[10] ;
  wire \in1[10] ;
  input \in1[11] ;
  wire \in1[11] ;
  input \in1[12] ;
  wire \in1[12] ;
  input \in1[13] ;
  wire \in1[13] ;
  input \in1[14] ;
  wire \in1[14] ;
  input \in1[15] ;
  wire \in1[15] ;
  input \in1[1] ;
  wire \in1[1] ;
  input \in1[2] ;
  wire \in1[2] ;
  input \in1[3] ;
  wire \in1[3] ;
  input \in1[4] ;
  wire \in1[4] ;
  input \in1[5] ;
  wire \in1[5] ;
  input \in1[6] ;
  wire \in1[6] ;
  input \in1[7] ;
  wire \in1[7] ;
  input \in1[8] ;
  wire \in1[8] ;
  input \in1[9] ;
  wire \in1[9] ;
  input \in2[0] ;
  wire \in2[0] ;
  input \in2[10] ;
  wire \in2[10] ;
  input \in2[11] ;
  wire \in2[11] ;
  input \in2[12] ;
  wire \in2[12] ;
  input \in2[13] ;
  wire \in2[13] ;
  input \in2[14] ;
  wire \in2[14] ;
  input \in2[15] ;
  wire \in2[15] ;
  input \in2[1] ;
  wire \in2[1] ;
  input \in2[2] ;
  wire \in2[2] ;
  input \in2[3] ;
  wire \in2[3] ;
  input \in2[4] ;
  wire \in2[4] ;
  input \in2[5] ;
  wire \in2[5] ;
  input \in2[6] ;
  wire \in2[6] ;
  input \in2[7] ;
  wire \in2[7] ;
  input \in2[8] ;
  wire \in2[8] ;
  input \in2[9] ;
  wire \in2[9] ;
  output \res[0] ;
  wire \res[0] ;
  output \res[10] ;
  wire \res[10] ;
  output \res[11] ;
  wire \res[11] ;
  output \res[12] ;
  wire \res[12] ;
  output \res[13] ;
  wire \res[13] ;
  output \res[14] ;
  wire \res[14] ;
  output \res[15] ;
  wire \res[15] ;
  output \res[16] ;
  wire \res[16] ;
  output \res[1] ;
  wire \res[1] ;
  output \res[2] ;
  wire \res[2] ;
  output \res[3] ;
  wire \res[3] ;
  output \res[4] ;
  wire \res[4] ;
  output \res[5] ;
  wire \res[5] ;
  output \res[6] ;
  wire \res[6] ;
  output \res[7] ;
  wire \res[7] ;
  output \res[8] ;
  wire \res[8] ;
  output \res[9] ;
  wire \res[9] ;
  XNOR2_X1 _203_ (
    .A(_119_),
    .B(_132_),
    .ZN(_145_)
  );
  INV_X1 _204_ (
    .A(_145_),
    .ZN(_189_)
  );
  XNOR2_X1 _205_ (
    .A(_135_),
    .B(_122_),
    .ZN(_146_)
  );
  NAND2_X1 _206_ (
    .A1(_121_),
    .A2(_134_),
    .ZN(_147_)
  );
  AND2_X1 _207_ (
    .A1(_120_),
    .A2(_133_),
    .ZN(_148_)
  );
  NAND2_X1 _208_ (
    .A1(_131_),
    .A2(_144_),
    .ZN(_149_)
  );
  XOR2_X1 _209_ (
    .A(_131_),
    .B(_144_),
    .Z(_150_)
  );
  AND2_X1 _210_ (
    .A1(_130_),
    .A2(_143_),
    .ZN(_151_)
  );
  XNOR2_X1 _211_ (
    .A(_127_),
    .B(_140_),
    .ZN(_152_)
  );
  XNOR2_X1 _212_ (
    .A(_126_),
    .B(_139_),
    .ZN(_153_)
  );
  NOR2_X1 _213_ (
    .A1(_189_),
    .A2(_153_),
    .ZN(_154_)
  );
  AOI21_X1 _214_ (
    .A(_154_),
    .B1(_126_),
    .B2(_139_),
    .ZN(_155_)
  );
  XOR2_X1 _215_ (
    .A(_155_),
    .B(_152_),
    .Z(_198_)
  );
  NOR2_X1 _216_ (
    .A1(_130_),
    .A2(_143_),
    .ZN(_156_)
  );
  NOR3_X1 _217_ (
    .A1(_198_),
    .A2(_151_),
    .A3(_156_),
    .ZN(_157_)
  );
  OAI21_X1 _218_ (
    .A(_150_),
    .B1(_157_),
    .B2(_151_),
    .ZN(_158_)
  );
  AND2_X1 _219_ (
    .A1(_158_),
    .A2(_149_),
    .ZN(_159_)
  );
  INV_X1 _220_ (
    .A(_159_),
    .ZN(_160_)
  );
  NOR2_X1 _221_ (
    .A1(_120_),
    .A2(_133_),
    .ZN(_161_)
  );
  NOR2_X1 _222_ (
    .A1(_148_),
    .A2(_161_),
    .ZN(_162_)
  );
  AOI21_X1 _223_ (
    .A(_148_),
    .B1(_160_),
    .B2(_162_),
    .ZN(_163_)
  );
  XOR2_X1 _224_ (
    .A(_121_),
    .B(_134_),
    .Z(_164_)
  );
  INV_X1 _225_ (
    .A(_164_),
    .ZN(_165_)
  );
  OAI21_X1 _226_ (
    .A(_147_),
    .B1(_163_),
    .B2(_165_),
    .ZN(_166_)
  );
  XNOR2_X1 _227_ (
    .A(_166_),
    .B(_146_),
    .ZN(_192_)
  );
  NOR2_X1 _228_ (
    .A1(_138_),
    .A2(_125_),
    .ZN(_167_)
  );
  NAND2_X1 _229_ (
    .A1(_138_),
    .A2(_125_),
    .ZN(_168_)
  );
  NAND2_X1 _230_ (
    .A1(_137_),
    .A2(_124_),
    .ZN(_169_)
  );
  OR2_X1 _231_ (
    .A1(_123_),
    .A2(_136_),
    .ZN(_170_)
  );
  NAND2_X1 _232_ (
    .A1(_123_),
    .A2(_136_),
    .ZN(_171_)
  );
  NAND2_X1 _233_ (
    .A1(_192_),
    .A2(_171_),
    .ZN(_172_)
  );
  NAND2_X1 _234_ (
    .A1(_172_),
    .A2(_170_),
    .ZN(_173_)
  );
  NAND2_X1 _235_ (
    .A1(_173_),
    .A2(_169_),
    .ZN(_174_)
  );
  OAI21_X1 _236_ (
    .A(_174_),
    .B1(_137_),
    .B2(_124_),
    .ZN(_175_)
  );
  AOI21_X1 _237_ (
    .A(_167_),
    .B1(_175_),
    .B2(_168_),
    .ZN(_196_)
  );
  XOR2_X1 _238_ (
    .A(_138_),
    .B(_125_),
    .Z(_176_)
  );
  XNOR2_X1 _239_ (
    .A(_175_),
    .B(_176_),
    .ZN(_195_)
  );
  XOR2_X1 _240_ (
    .A(_137_),
    .B(_124_),
    .Z(_177_)
  );
  XNOR2_X1 _241_ (
    .A(_173_),
    .B(_177_),
    .ZN(_194_)
  );
  NAND2_X1 _242_ (
    .A1(_170_),
    .A2(_171_),
    .ZN(_178_)
  );
  XOR2_X1 _243_ (
    .A(_192_),
    .B(_178_),
    .Z(_193_)
  );
  XNOR2_X1 _244_ (
    .A(_163_),
    .B(_164_),
    .ZN(_191_)
  );
  INV_X1 _245_ (
    .A(_158_),
    .ZN(_179_)
  );
  NOR3_X1 _246_ (
    .A1(_157_),
    .A2(_150_),
    .A3(_151_),
    .ZN(_180_)
  );
  NOR2_X1 _247_ (
    .A1(_179_),
    .A2(_180_),
    .ZN(_202_)
  );
  NAND2_X1 _248_ (
    .A1(_128_),
    .A2(_141_),
    .ZN(_181_)
  );
  NOR2_X1 _249_ (
    .A1(_128_),
    .A2(_141_),
    .ZN(_182_)
  );
  NOR2_X1 _250_ (
    .A1(_155_),
    .A2(_152_),
    .ZN(_183_)
  );
  AOI21_X1 _251_ (
    .A(_183_),
    .B1(_127_),
    .B2(_140_),
    .ZN(_184_)
  );
  OAI21_X1 _252_ (
    .A(_181_),
    .B1(_184_),
    .B2(_182_),
    .ZN(_185_)
  );
  XNOR2_X1 _253_ (
    .A(_142_),
    .B(_129_),
    .ZN(_186_)
  );
  XNOR2_X1 _254_ (
    .A(_185_),
    .B(_186_),
    .ZN(_200_)
  );
  XOR2_X1 _255_ (
    .A(_128_),
    .B(_141_),
    .Z(_187_)
  );
  XNOR2_X1 _256_ (
    .A(_184_),
    .B(_187_),
    .ZN(_199_)
  );
  XNOR2_X1 _257_ (
    .A(_145_),
    .B(_153_),
    .ZN(_197_)
  );
  NOR2_X1 _258_ (
    .A1(_151_),
    .A2(_156_),
    .ZN(_188_)
  );
  XNOR2_X1 _259_ (
    .A(_198_),
    .B(_188_),
    .ZN(_201_)
  );
  XNOR2_X1 _260_ (
    .A(_159_),
    .B(_162_),
    .ZN(_190_)
  );
  assign \res[1]  = 1'h1;
  assign \res[2]  = 1'h0;
  assign \res[7]  = 1'h1;
  assign _135_ = \in2[12] ;
  assign _122_ = \in1[12] ;
  assign _130_ = \in1[8] ;
  assign _143_ = \in2[8] ;
  assign _127_ = \in1[4] ;
  assign _140_ = \in2[4] ;
  assign _126_ = \in1[3] ;
  assign _119_ = \in1[0] ;
  assign _132_ = \in2[0] ;
  assign \res[0]  = _189_;
  assign _139_ = \in2[3] ;
  assign _121_ = \in1[11] ;
  assign _134_ = \in2[11] ;
  assign _120_ = \in1[10] ;
  assign _133_ = \in2[10] ;
  assign _131_ = \in1[9] ;
  assign _144_ = \in2[9] ;
  assign \res[12]  = _192_;
  assign \res[4]  = _198_;
  assign _138_ = \in2[15] ;
  assign _125_ = \in1[15] ;
  assign _137_ = \in2[14] ;
  assign _124_ = \in1[14] ;
  assign _123_ = \in1[13] ;
  assign _136_ = \in2[13] ;
  assign \res[16]  = _196_;
  assign \res[15]  = _195_;
  assign \res[14]  = _194_;
  assign \res[13]  = _193_;
  assign \res[11]  = _191_;
  assign \res[9]  = _202_;
  assign _142_ = \in2[6] ;
  assign _129_ = \in1[6] ;
  assign _128_ = \in1[5] ;
  assign _141_ = \in2[5] ;
  assign \res[6]  = _200_;
  assign \res[5]  = _199_;
  assign \res[3]  = _197_;
  assign \res[8]  = _201_;
  assign \res[10]  = _190_;
endmodule
