/* Generated by Yosys 0.18+29 (git sha1 b2408df31, gcc 10.3.0-1ubuntu1~20.04 -fPIC -Os) */

module adder16(\in1[0] , \in1[1] , \in1[2] , \in1[3] , \in1[4] , \in1[5] , \in1[6] , \in1[7] , \in1[8] , \in1[9] , \in1[10] , \in1[11] , \in1[12] , \in1[13] , \in1[14] , \in1[15] , \in2[0] , \in2[1] , \in2[2] , \in2[3] , \in2[4] 
, \in2[5] , \in2[6] , \in2[7] , \in2[8] , \in2[9] , \in2[10] , \in2[11] , \in2[12] , \in2[13] , \in2[14] , \in2[15] , \res[0] , \res[1] , \res[2] , \res[3] , \res[4] , \res[5] , \res[6] , \res[7] , \res[8] , \res[9] 
, \res[10] , \res[11] , \res[12] , \res[13] , \res[14] , \res[15] , \res[16] );
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  input \in1[0] ;
  wire \in1[0] ;
  input \in1[10] ;
  wire \in1[10] ;
  input \in1[11] ;
  wire \in1[11] ;
  input \in1[12] ;
  wire \in1[12] ;
  input \in1[13] ;
  wire \in1[13] ;
  input \in1[14] ;
  wire \in1[14] ;
  input \in1[15] ;
  wire \in1[15] ;
  input \in1[1] ;
  wire \in1[1] ;
  input \in1[2] ;
  wire \in1[2] ;
  input \in1[3] ;
  wire \in1[3] ;
  input \in1[4] ;
  wire \in1[4] ;
  input \in1[5] ;
  wire \in1[5] ;
  input \in1[6] ;
  wire \in1[6] ;
  input \in1[7] ;
  wire \in1[7] ;
  input \in1[8] ;
  wire \in1[8] ;
  input \in1[9] ;
  wire \in1[9] ;
  input \in2[0] ;
  wire \in2[0] ;
  input \in2[10] ;
  wire \in2[10] ;
  input \in2[11] ;
  wire \in2[11] ;
  input \in2[12] ;
  wire \in2[12] ;
  input \in2[13] ;
  wire \in2[13] ;
  input \in2[14] ;
  wire \in2[14] ;
  input \in2[15] ;
  wire \in2[15] ;
  input \in2[1] ;
  wire \in2[1] ;
  input \in2[2] ;
  wire \in2[2] ;
  input \in2[3] ;
  wire \in2[3] ;
  input \in2[4] ;
  wire \in2[4] ;
  input \in2[5] ;
  wire \in2[5] ;
  input \in2[6] ;
  wire \in2[6] ;
  input \in2[7] ;
  wire \in2[7] ;
  input \in2[8] ;
  wire \in2[8] ;
  input \in2[9] ;
  wire \in2[9] ;
  output \res[0] ;
  wire \res[0] ;
  output \res[10] ;
  wire \res[10] ;
  output \res[11] ;
  wire \res[11] ;
  output \res[12] ;
  wire \res[12] ;
  output \res[13] ;
  wire \res[13] ;
  output \res[14] ;
  wire \res[14] ;
  output \res[15] ;
  wire \res[15] ;
  output \res[16] ;
  wire \res[16] ;
  output \res[1] ;
  wire \res[1] ;
  output \res[2] ;
  wire \res[2] ;
  output \res[3] ;
  wire \res[3] ;
  output \res[4] ;
  wire \res[4] ;
  output \res[5] ;
  wire \res[5] ;
  output \res[6] ;
  wire \res[6] ;
  output \res[7] ;
  wire \res[7] ;
  output \res[8] ;
  wire \res[8] ;
  output \res[9] ;
  wire \res[9] ;
  XNOR2_X1 _087_ (
    .A(_048_),
    .B(_057_),
    .ZN(_085_)
  );
  NAND2_X1 _088_ (
    .A1(_049_),
    .A2(_058_),
    .ZN(_059_)
  );
  OR2_X1 _089_ (
    .A1(_048_),
    .A2(_057_),
    .ZN(_060_)
  );
  OR2_X1 _090_ (
    .A1(_049_),
    .A2(_058_),
    .ZN(_061_)
  );
  NAND2_X1 _091_ (
    .A1(_060_),
    .A2(_061_),
    .ZN(_062_)
  );
  NAND2_X1 _092_ (
    .A1(_062_),
    .A2(_059_),
    .ZN(_063_)
  );
  XNOR2_X1 _093_ (
    .A(_051_),
    .B(_042_),
    .ZN(_064_)
  );
  XNOR2_X1 _094_ (
    .A(_063_),
    .B(_064_),
    .ZN(_079_)
  );
  XNOR2_X1 _095_ (
    .A(_054_),
    .B(_045_),
    .ZN(_065_)
  );
  NOR2_X1 _096_ (
    .A1(_044_),
    .A2(_053_),
    .ZN(_066_)
  );
  NOR2_X1 _097_ (
    .A1(_043_),
    .A2(_052_),
    .ZN(_067_)
  );
  XOR2_X1 _098_ (
    .A(_043_),
    .B(_052_),
    .Z(_068_)
  );
  AOI21_X1 _099_ (
    .A(_067_),
    .B1(_079_),
    .B2(_068_),
    .ZN(_069_)
  );
  XNOR2_X1 _100_ (
    .A(_044_),
    .B(_053_),
    .ZN(_070_)
  );
  NOR2_X1 _101_ (
    .A1(_069_),
    .A2(_070_),
    .ZN(_071_)
  );
  NOR2_X1 _102_ (
    .A1(_071_),
    .A2(_066_),
    .ZN(_072_)
  );
  XNOR2_X1 _103_ (
    .A(_072_),
    .B(_065_),
    .ZN(_082_)
  );
  XNOR2_X1 _104_ (
    .A(_069_),
    .B(_070_),
    .ZN(_081_)
  );
  XNOR2_X1 _105_ (
    .A(_079_),
    .B(_068_),
    .ZN(_080_)
  );
  NAND2_X1 _106_ (
    .A1(_061_),
    .A2(_059_),
    .ZN(_073_)
  );
  XNOR2_X1 _107_ (
    .A(_073_),
    .B(_060_),
    .ZN(_086_)
  );
  NOR2_X1 _108_ (
    .A1(_041_),
    .A2(_050_),
    .ZN(_074_)
  );
  AND2_X1 _109_ (
    .A1(_041_),
    .A2(_050_),
    .ZN(_075_)
  );
  NOR2_X1 _110_ (
    .A1(_075_),
    .A2(_074_),
    .ZN(_078_)
  );
  XOR2_X1 _111_ (
    .A(_078_),
    .B(_047_),
    .Z(_076_)
  );
  XNOR2_X1 _112_ (
    .A(_076_),
    .B(_056_),
    .ZN(_084_)
  );
  XNOR2_X1 _113_ (
    .A(_055_),
    .B(_046_),
    .ZN(_077_)
  );
  XNOR2_X1 _114_ (
    .A(_077_),
    .B(_075_),
    .ZN(_083_)
  );
  assign \res[11]  = 1'h1;
  assign \res[12]  = 1'h0;
  assign \res[16]  = 1'h1;
  assign \res[2]  = 1'h0;
  assign \res[4]  = 1'h0;
  assign \res[5]  = 1'h1;
  assign \res[6]  = 1'h1;
  assign \res[7]  = 1'h1;
  assign _048_ = \in1[8] ;
  assign _057_ = \in2[8] ;
  assign \res[8]  = _085_;
  assign _051_ = \in2[10] ;
  assign _042_ = \in1[10] ;
  assign _049_ = \in1[9] ;
  assign _058_ = \in2[9] ;
  assign \res[10]  = _079_;
  assign _054_ = \in2[15] ;
  assign _045_ = \in1[15] ;
  assign _043_ = \in1[13] ;
  assign _052_ = \in2[13] ;
  assign _044_ = \in1[14] ;
  assign _053_ = \in2[14] ;
  assign \res[15]  = _082_;
  assign \res[14]  = _081_;
  assign \res[13]  = _080_;
  assign \res[9]  = _086_;
  assign _047_ = \in1[3] ;
  assign _056_ = \in2[3] ;
  assign _041_ = \in1[0] ;
  assign _050_ = \in2[0] ;
  assign \res[3]  = _084_;
  assign _055_ = \in2[1] ;
  assign _046_ = \in1[1] ;
  assign \res[1]  = _083_;
  assign \res[0]  = _078_;
endmodule
